# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 05:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchfilm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('describ', models.TextField(verbose_name='\u7b80\u8ff0')),
                ('url', models.URLField(verbose_name='\u94fe\u63a5')),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(verbose_name='\u6dfb\u52a0\u7684\u7535\u5f71')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovieSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.IntegerField(verbose_name='\u770b\u8fc7\u7684\u7535\u5f71')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
