# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchfilm', '0002_useraddlist_usermovielist_usermovieseen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddlist',
            name='describ',
        ),
        migrations.AddField(
            model_name='useraddlist',
            name='describe',
            field=models.TextField(blank=True, null=True, verbose_name='\u7b80\u8ff0'),
        ),
    ]
