# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-22 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchfilm', '0003_auto_20161222_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddlist',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
