# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-23 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchfilm', '0004_useraddlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddlist',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u5f71\u89c6\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='usermovieseen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
