# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchfilm', '0005_auto_20161223_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\dell\\Desktop\\watchfilms\\media\\avatar', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
